export const videos = [
  {
    _id: "1",
    videotitle: "Amazing Nature Documentary",
    filename: "nature.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "500MB",
    videochannel: "Nature Channel",
    like: 1250,
    views: 45000,
    uploader: "Nature",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "2",
    videotitle: "Cooking Tutorial: Perfect Pasta",
    filename: "pasta.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "300MB",
    videochannel: "Chef's Kitchen",
    like: 890,
    views: 23000,
    uploader: "Chef",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: "3",
    videotitle: "React JS Crash Course",
    filename: "react.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "600MB",
    videochannel: "Code Academy",
    like: 2400,
    views: 92000,
    uploader: "Developer",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: "4",
    videotitle: "Top 10 Travel Destinations",
    filename: "travel.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "450MB",
    videochannel: "Travel World",
    like: 1800,
    views: 61000,
    uploader: "Traveller",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    _id: "5",
    videotitle: "Learn Next.js in One Hour",
    filename: "nextjs.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "700MB",
    videochannel: "Programming Hub",
    like: 3150,
    views: 154000,
    uploader: "CodeHub",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    _id: "6",
    videotitle: "JavaScript Interview Questions",
    filename: "javascript.mp4",
    filetype: "video/mp4",
    filepath: "/video/vdo.mp4",
    filesize: "550MB",
    videochannel: "Tech World",
    like: 980,
    views: 34000,
    uploader: "TechGuru",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
];